# Generated by Django 4.2.7 on 2024-07-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_name', models.CharField(max_length=255)),
                ('test_case_verdict', models.CharField(max_length=255)),
                ('domain_expert_of_requirement', models.CharField(max_length=255)),
                ('artifactory_upload_paths', models.CharField(max_length=255)),
                ('used_tbc', models.CharField(max_length=255)),
                ('report_id_atx_id', models.CharField(max_length=255)),
                ('hw_sample', models.CharField(max_length=255)),
            ],
        ),
    ]
